[package]
name = "macro_ref"
version = "0.1.0"
authors = ["franktly <franktaolingyang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
